# Use an official Node runtime
FROM node:alpine

# Create app directory
WORKDIR /app

# Copy just one file
COPY ./file-promise2.js .
#COPY ./input.txt .

# Start the app
CMD ["node", "file-promise2.js"]
