const express = require('express');
const { Pool } = require("pg"); // destructuring same as pg.Pool

const app = express();
app.use(express.json());

const pool = new Pool({
  host: process.env.DB_HOST || 'localhost',
  user: "admin",
  password: "admin",
  database: "pg_demo_db"
});

const PORT = 3000;


// Create table
app.get('/create-table', async (req, res) => {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS people (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name VARCHAR(30) NOT NULL,
        last_name VARCHAR(30) NOT NULL,
        age INT NOT NULL
      );
    `);
    res.json({ message: "Table created" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Insert data
app.post('/people', async (req, res) => {
  const { first_name: fName, last_name: lName, age } = req.body; // Destructure and rename just to demo

  try {
    const result = await pool.query(
    //  `INSERT INTO people (first_name, last_name, age) VALUES ('${fName}','${lName}','${age}') RETURNING *` // RETURNING is non-standard
      `INSERT INTO people (first_name, last_name, age) VALUES ($1, $2, $3) RETURNING *`, [fName, lName, age]
    );
    res.json(result.rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Read data
app.get('/people', async (req, res) => {
  try {
    const result = await pool.query("SELECT * FROM people");
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/people', async (req, res) => {
  try {
    const result = await pool.query('DROP TABLE IF EXISTS people');
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.listen(3000, () => console.log(`Server listening on port ${PORT}`));
