services:
   pg_demo:
    build:
      context: .
    image: pg_demo
    container_name: pg_demo
    ports:
      - "4000:3000"
    environment:
       DB_HOST: pg
    #   DB_USER: admin
    #   DB_PASSWORD: admin
    #   DB_NAME: people
    depends_on:
      - pg

   pg:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg_demo_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
